#!/bin/sh
echo "-----> Clearing Heroku cache"
curl -n -X DELETE https://api.heroku.com/apps/$HEROKU_APP_NAME/build-cache -H "Authorization: Bearer $HEROKU_API_KEY" -H "Accept: application/vnd.heroku+json; version=3"