import { useTranslation } from 'react-i18next';

const CitySelector = () => {
    const { t } = useTranslation();

    const cities = [
        { "label": t('Sofia'), "value": t('Sofia') },
        { "label": t('Plovdiv'), "value": t('Plovdiv') },
        { "label": t('Varna'), "value": t('Varna') },
        { "label": t('Burgas'), "value": t('Burgas') },
        { "label": t('Ruse'), "value": t('Ruse') },
        { "label": t('Stara Zagora'), "value": t('Stara Zagora') },
        { "label": t('Pleven'), "value": t('Pleven') },
        { "label": t('Sliven'), "value": t('Sliven') },
        { "label": t('Pazardzhik'), "value": t('Pazardzhik') },
        { "label": t('Pernik'), "value": t('Pernik') },
        { "label": t('Dobrich'), "value": t('Dobrich') },
        { "label": t('Shumen'), "value": t('Shumen') },
        { "label": t('Veliko Tarnovo'), "value": t('Veliko Tarnovo') },
        { "label": t('Haskovo'), "value": t('Haskovo') },
        { "label": t('Blagoevgrad'), "value": t('Blagoevgrad') },
        { "label": t('Yambol'), "value": t('Yambol') },
        { "label": t('Kazanlak'), "value": t('Kazanlak') },
        { "label": t('Asenovgrad'), "value": t('Asenovgrad') },
        { "label": t('Vratsa'), "value": t('Vratsa') },
        { "label": t('Kyustendil'), "value": t('Kyustendil') },
        { "label": t('Gabrovo'), "value": t('Gabrovo') },
        { "label": t('Targovishte'), "value": t('Targovishte') },
        { "label": t('Kardzhali'), "value": t('Kardzhali') },
        { "label": t('Vidin'), "value": t('Vidin') },
        { "label": t('Razgrad'), "value": t('Razgrad') },
        { "label": t('Svishtov'), "value": t('Svishtov') },
        { "label": t('Silistra'), "value": t('Silistra') },
        { "label": t('Lovech'), "value": t('Lovech') },
        { "label": t('Montana'), "value": t('Montana') },
        { "label": t('Dimitrovgrad'), "value": t('Dimitrovgrad') },
        { "label": t('Dupnitsa'), "value": t('Dupnitsa') },
        { "label": t('Smolyan'), "value": t('Smolyan') },
        { "label": t('Gorna Oryahovitsa'), "value": t('Gorna Oryahovitsa') },
        { "label": t('Petrich'), "value": t('Petrich') },
        { "label": t('Gotse Delchev'), "value": t('Gotse Delchev') },
        { "label": t('Aytos'), "value": t('Aytos') },
        { "label": t('Omurtag'), "value": t('Omurtag') },
        { "label": t('Velingrad'), "value": t('Velingrad') },
        { "label": t('Isperih'), "value": t('Isperih') },
        { "label": t('Karlovo'), "value": t('Karlovo') },
        { "label": t('Lom'), "value": t('Lom') },
        { "label": t('Panagyurishte'), "value": t('Panagyurishte') },
        { "label": t('Botevgrad'), "value": t('Botevgrad') },
        { "label": t('Peshtera'), "value": t('Peshtera') },
        { "label": t('Rakovski'), "value": t('Rakovski') },
        { "label": t('Veliki Preslav'), "value": t('Veliki Preslav') },
        { "label": t('Pomorie'), "value": t('Pomorie') },
        { "label": t('Lyaskovets'), "value": t('Lyaskovets') },
        { "label": t('Novi Pazar'), "value": t('Novi Pazar') },
        { "label": t('Provadia'), "value": t('Provadia') },
        { "label": t('Razlog'), "value": t('Razlog') },
        { "label": t('Zlatograd'), "value": t('Zlatograd') },
        { "label": t('Kozloduy'), "value": t('Kozloduy') },
        { "label": t('Kostinbrod'), "value": t('Kostinbrod') },
        { "label": t('Bankya'), "value": t('Bankya') },
        { "label": t('Stamboliyski'), "value": t('Stamboliyski') },
        { "label": t('Etropole'), "value": t('Etropole') },
        { "label": t('Devnya'), "value": t('Devnya') },
        { "label": t('Rakitovo'), "value": t('Rakitovo') },
        { "label": t('Sopot'), "value": t('Sopot') },
        { "label": t('Septemvri'), "value": t('Septemvri') },
        { "label": t('Krichim'), "value": t('Krichim') },
        { "label": t('Byala'), "value": t('Byala') },
        { "label": t('Aksakovo'), "value": t('Aksakovo') },
        { "label": t('Beloslav'), "value": t('Beloslav') },
        { "label": t('Slivnitsa'), "value": t('Slivnitsa') },
        { "label": t('Elin Pelin'), "value": t('Elin Pelin') },
        { "label": t('Madan'), "value": t('Madan') },
        { "label": t('Aydemir'), "value": t('Aydemir') },
        { "label": t('Devin'), "value": t('Devin') },
        { "label": t('Lozen'), "value": t('Lozen') },
        { "label": t('Varshets'), "value": t('Varshets') },
        { "label": t('Saedinenie'), "value": t('Saedinenie') },
        { "label": t('Bistritsa'), "value": t('Bistritsa') },
        { "label": t('Bozhurishte'), "value": t('Bozhurishte') },
        { "label": t('Suvorovo'), "value": t('Suvorovo') },
        { "label": t('Perushtitsa'), "value": t('Perushtitsa') },
        { "label": t('Dolna Banya'), "value": t('Dolna Banya') },
        { "label": t('Vetovo'), "value": t('Vetovo') },
        { "label": t('Kazichene'), "value": t('Kazichene') },
        { "label": t('Ignatievo'), "value": t('Ignatievo') },
        { "label": t('Kostandovo'), "value": t('Kostandovo') },
        { "label": t('Bukovlak'), "value": t('Bukovlak') },
        { "label": t('Koynare'), "value": t('Koynare') },
        { "label": t('Slavyanovo'), "value": t('Slavyanovo') },
        { "label": t('Kalipetrovo'), "value": t('Kalipetrovo') },
        { "label": t('Trud'), "value": t('Trud') },
        { "label": t('Sveti Vlas'), "value": t('Sveti Vlas') },
        { "label": t('Sapareva Banya'), "value": t('Sapareva Banya') },
        { "label": t('Malo Konare'), "value": t('Malo Konare') },
        { "label": t('Varbitsa'), "value": t('Varbitsa') },
        { "label": t('Marten'), "value": t('Marten') },
        { "label": t('Debelets'), "value": t('Debelets') },
        { "label": t('Vladaya'), "value": t('Vladaya') },
        { "label": t('Parvenets'), "value": t('Parvenets') },
        { "label": t('Sarnitsa'), "value": t('Sarnitsa') },
        { "label": t('Rudozem'), "value": t('Rudozem') },
        { "label": t('Topolchane'), "value": t('Topolchane') },
        { "label": t('Brestovitsa'), "value": t('Brestovitsa') },
        { "label": t('Gulyantsi'), "value": t('Gulyantsi') },
        { "label": t('Nikolaevo'), "value": t('Nikolaevo') },
        { "label": t('Rogosh'), "value": t('Rogosh') },
        { "label": t('Kran'), "value": t('Kran') },
        { "label": t('Banya'), "value": t('Banya') },
        { "label": t('Topoli'), "value": t('Topoli') },
        { "label": t('Pancharevo'), "value": t('Pancharevo') },
        { "label": t('Kamenar'), "value": t('Kamenar') },
        { "label": t('Gurkovo'), "value": t('Gurkovo') },
        { "label": t('Ivaylo'), "value": t('Ivaylo') },
        { "label": t('Sotirya'), "value": t('Sotirya') },
        { "label": t('Kableshkovo'), "value": t('Kableshkovo') },
        { "label": t('Ruen'), "value": t('Ruen') },
        { "label": t('Vetren'), "value": t('Vetren') },
        { "label": t('Dolna Oryahovitsa'), "value": t('Dolna Oryahovitsa') },
        { "label": t('Buhovo'), "value": t('Buhovo') },
        { "label": t('Kalofer'), "value": t('Kalofer') },
        { "label": t('Voluyak'), "value": t('Voluyak') },
        { "label": t('Kalekovets'), "value": t('Kalekovets') },
        { "label": t('German'), "value": t('German') },
        { "label": t('Nikolovo'), "value": t('Nikolovo') },
        { "label": t('Ravda'), "value": t('Ravda') },
        { "label": t('Glozhene'), "value": t('Glozhene') },
        { "label": t('Novo Selo'), "value": t('Novo Selo') },
        { "label": t('Kurtovo Konare'), "value": t('Kurtovo Konare') },
        { "label": t('Ablanitsa'), "value": t('Ablanitsa') },
        { "label": t('Skutare'), "value": t('Skutare') },
        { "label": t('Sadovo'), "value": t('Sadovo') },
        { "label": t('Chepintsi'), "value": t('Chepintsi') },
        { "label": t('Parvomaytsi'), "value": t('Parvomaytsi') }, { "label": t('Draganovo'), "value": t('Draganovo') },
        { "label": t('Kilifarevo'), "value": t('Kilifarevo') },
        { "label": t('Ognyanovo'), "value": t('Ognyanovo') },
        { "label": t('Valkosel'), "value": t('Valkosel') },
        { "label": t('Rakovski'), "value": t('Rakovski') },
        { "label": t('Glavinitsa'), "value": t('Glavinitsa') },
        { "label": t('Bregovo'), "value": t('Bregovo') },
        { "label": t('Svetovrachane'), "value": t('Svetovrachane') },
        { "label": t('Aheloy'), "value": t('Aheloy') },
        { "label": t('Krushare'), "value": t('Krushare') },
        { "label": t('Startsevo'), "value": t('Startsevo') },
        { "label": t('Gradina'), "value": t('Gradina') },
        { "label": t('Obzor'), "value": t('Obzor') },
        { "label": t('Batanovtsi'), "value": t('Batanovtsi') },
        { "label": t('Tsaratsovo'), "value": t('Tsaratsovo') },
        { "label": t('Borovo'), "value": t('Borovo') },
        { "label": t('Voyvodinovo'), "value": t('Voyvodinovo') },
        { "label": t('Chernogorovo'), "value": t('Chernogorovo') },
        { "label": t('Balgarovo'), "value": t('Balgarovo') },
        { "label": t('Petarch'), "value": t('Petarch') },
        { "label": t('Kokalyane'), "value": t('Kokalyane') },
        { "label": t('Dragichevo'), "value": t('Dragichevo') },
        { "label": t('Yahinovo'), "value": t('Yahinovo') },
        { "label": t('Ostrovo'), "value": t('Ostrovo') },
        { "label": t('Mokrishte'), "value": t('Mokrishte') },
        { "label": t('Kraynitsi'), "value": t('Kraynitsi') },
        { "label": t('Kostievo'), "value": t('Kostievo') },
        { "label": t('Resen'), "value": t('Resen') },
        { "label": t('Aleksandrovo'), "value": t('Aleksandrovo') },
        { "label": t('Sinitovo'), "value": t('Sinitovo') },
        { "label": t('Ezerovo'), "value": t('Ezerovo') },
        { "label": t('Graf Ignatievo'), "value": t('Graf Ignatievo') },
        { "label": t('Seliminovo'), "value": t('Seliminovo') },
        { "label": t('Uzundzhovo'), "value": t('Uzundzhovo') },
        { "label": t('Busmantsi'), "value": t('Busmantsi') },
        { "label": t('Polikrayshte'), "value": t('Polikrayshte') },
        { "label": t('Lesnovo'), "value": t('Lesnovo') },
        { "label": t('Merichleri'), "value": t('Merichleri') },
        { "label": t('Lyuben Karavelovo'), "value": t('Lyuben Karavelovo') },
        { "label": t('Divotino'), "value": t('Divotino') },
        { "label": t('Byal Izvor'), "value": t('Byal Izvor') },
        { "label": t('Kermen'), "value": t('Kermen') },
        { "label": t('Ravnets'), "value": t('Ravnets') },
        { "label": t('Kukorevo'), "value": t('Kukorevo') },
        { "label": t('Samoranovo'), "value": t('Samoranovo') },
        { "label": t('Stozher'), "value": t('Stozher') },
        { "label": t('Dzhulyunitsa'), "value": t('Dzhulyunitsa') },
        { "label": t('Zheleznitsa'), "value": t('Zheleznitsa') },
        { "label": t('Slokoshtitsa'), "value": t('Slokoshtitsa') },
        { "label": t('Orizare'), "value": t('Orizare') },
        { "label": t('Negovan'), "value": t('Negovan') },
        { "label": t('Trivoditsi'), "value": t('Trivoditsi') },
        { "label": t('Krepost'), "value": t('Krepost') },
        { "label": t('Grivitsa'), "value": t('Grivitsa') },
        { "label": t('Studena'), "value": t('Studena') },
        { "label": t('Bistritsa'), "value": t('Bistritsa') },
        { "label": t('Stratsin'), "value": t('Stratsin') },
        { "label": t('Mirovyane'), "value": t('Mirovyane') },
        { "label": t('Saraya'), "value": t('Saraya') },
        { "label": t('Planinitsa'), "value": t('Planinitsa') },
        { "label": t('Krivina'), "value": t('Krivina') },
        { "label": t('Karageorgievo'), "value": t('Karageorgievo') },
        { "label": t('Prosenik'), "value": t('Prosenik') },
        { "label": t('Vinogradets'), "value": t('Vinogradets') },
        { "label": t('Tsarev Brod'), "value": t('Tsarev Brod') },
        { "label": t('Tankovo'), "value": t('Tankovo') },
        { "label": t('Maglen'), "value": t('Maglen') },
        { "label": t('Tranak'), "value": t('Tranak') },
        { "label": t('Razhitsa'), "value": t('Razhitsa') },
        { "label": t('Dzherman'), "value": t('Dzherman') },
        { "label": t('Shipka'), "value": t('Shipka') },
        { "label": t('Basarbovo'), "value": t('Basarbovo') },
        { "label": t('Karabunar'), "value": t('Karabunar') },
        { "label": t('Benkovski'), "value": t('Benkovski') },
        { "label": t('Kosharitsa'), "value": t('Kosharitsa') },
        { "label": t('Konstantinovo'), "value": t('Konstantinovo') },
        { "label": t('Yabalchevo'), "value": t('Yabalchevo') },
        { "label": t('Galabets'), "value": t('Galabets') },
        { "label": t('Chervena Voda'), "value": t('Chervena Voda') },
        { "label": t('Veselinovo'), "value": t('Veselinovo') },
        { "label": t('Bata'), "value": t('Bata') },
        { "label": t('Rudartsi'), "value": t('Rudartsi') },
        { "label": t('Dolni Bogrov'), "value": t('Dolni Bogrov') },
        { "label": t('Aldomirovtsi'), "value": t('Aldomirovtsi') },
        { "label": t('Belogradets'), "value": t('Belogradets') },
        { "label": t('Karapelit'), "value": t('Karapelit') },
        { "label": t('Novo Selo'), "value": t('Novo Selo') },
        { "label": t('Sandrovo'), "value": t('Sandrovo') },
        { "label": t('Yabalkovo'), "value": t('Yabalkovo') },
        { "label": t('Gabrovnitsa'), "value": t('Gabrovnitsa') },
        { "label": t('Vaglen'), "value": t('Vaglen') },
        { "label": t('Vardun'), "value": t('Vardun') },
        { "label": t('Marchaevo'), "value": t('Marchaevo') },
        { "label": t('Banitsa'), "value": t('Banitsa') },
        { "label": t('Gorni Bogrov'), "value": t('Gorni Bogrov') },
        { "label": t('Semerdzhievo'), "value": t('Semerdzhievo') },
        { "label": t('Zaychar'), "value": t('Zaychar') },
        { "label": t('Voyvodovo'), "value": t('Voyvodovo') },
        { "label": t('Malevo'), "value": t('Malevo') },
        { "label": t('Opalchensko'), "value": t('Opalchensko') },
        { "label": t('Zvezditsa'), "value": t('Zvezditsa') },
        { "label": t('Marinka'), "value": t('Marinka') },
        { "label": t('Boboshevo'), "value": t('Boboshevo') },
        { "label": t('Gyulyovtsa'), "value": t('Gyulyovtsa') },
        { "label": t('Gluhar'), "value": t('Gluhar') },
        { "label": t('Hadzhievo'), "value": t('Hadzhievo') },
        { "label": t('Pisarevo'), "value": t('Pisarevo') },
        { "label": t('Vaklinovo'), "value": t('Vaklinovo') },
        { "label": t('Varbitsa'), "value": t('Varbitsa') },
        { "label": t('Kladnitsa'), "value": t('Kladnitsa') },
        { "label": t('Patalenitsa'), "value": t('Patalenitsa') },
        { "label": t('Dolen'), "value": t('Dolen') },
        { "label": t('Dobromir'), "value": t('Dobromir') },
        { "label": t('Dobri Dyal'), "value": t('Dobri Dyal') },
        { "label": t('Gorski Izvor'), "value": t('Gorski Izvor') },
        { "label": t('Stefanovo'), "value": t('Stefanovo') },
        { "label": t('Borovo'), "value": t('Borovo') },
        { "label": t('Cherven Breg'), "value": t('Cherven Breg') },
        { "label": t('Snyagovo'), "value": t('Snyagovo') },
        { "label": t('Krastava'), "value": t('Krastava') },
        { "label": t('Kadievo'), "value": t('Kadievo') },
        { "label": t('Voysil'), "value": t('Voysil') },
        { "label": t('Vresovo'), "value": t('Vresovo') },
        { "label": t('Vinitsa'), "value": t('Vinitsa') },
        { "label": t('Mortagonovo'), "value": t('Mortagonovo') },
        { "label": t('Izvorsko'), "value": t('Izvorsko') },
        { "label": t('Dobroslavtsi'), "value": t('Dobroslavtsi') },

    ];

    return cities;
};

export default CitySelector;
