import { useTranslation } from 'react-i18next';

const CitySelector = () => {
    const { t } = useTranslation();

    const cities = [
        { "label": t('Sofia'), "value": t('Sofia') },
        { "label": t('Plovdiv'), "value": t('Plovdiv') },
        { "label": t('Varna'), "value": t('Varna') },
        { "label": t('Burgas'), "value": t('Burgas') },
        { "label": t('Ruse'), "value": t('Ruse') },
        { "label": t('Stara Zagora'), "value": t('Stara Zagora') },
        { "label": t('Pleven'), "value": t('Pleven') },
        { "label": t('Sliven'), "value": t('Sliven') },
        { "label": t('Pazardzhik'), "value": t('Pazardzhik') },
        { "label": t('Pernik'), "value": t('Pernik') },
        { "label": t('Dobrich'), "value": t('Dobrich') },
        { "label": t('Shumen'), "value": t('Shumen') },
        { "label": t('Veliko Tarnovo'), "value": t('Veliko Tarnovo') },
        { "label": t('Haskovo'), "value": t('Haskovo') },
        { "label": t('Blagoevgrad'), "value": t('Blagoevgrad') },
        { "label": t('Yambol'), "value": t('Yambol') },
        { "label": t('Kazanlak'), "value": t('Kazanlak') },
        { "label": t('Asenovgrad'), "value": t('Asenovgrad') },
        { "label": t('Vratsa'), "value": t('Vratsa') },
        { "label": t('Kyustendil'), "value": t('Kyustendil') },
        { "label": t('Gabrovo'), "value": t('Gabrovo') },
        { "label": t('Targovishte'), "value": t('Targovishte') },
        { "label": t('Kardzhali'), "value": t('Kardzhali') },
        { "label": t('Vidin'), "value": t('Vidin') },
        { "label": t('Razgrad'), "value": t('Razgrad') },
        { "label": t('Svishtov'), "value": t('Svishtov') },
        { "label": t('Silistra'), "value": t('Silistra') },
        { "label": t('Lovech'), "value": t('Lovech') },
        { "label": t('Montana'), "value": t('Montana') },
        { "label": t('Dimitrovgrad'), "value": t('Dimitrovgrad') },
        { "label": t('Dupnitsa'), "value": t('Dupnitsa') },
        { "label": t('Smolyan'), "value": t('Smolyan') },
        { "label": t('Gorna Oryahovitsa'), "value": t('Gorna Oryahovitsa') },
        { "label": t('Petrich'), "value": t('Petrich') },
        { "label": t('Gotse Delchev'), "value": t('Gotse Delchev') },
        { "label": t('Aytos'), "value": t('Aytos') },
        { "label": t('Omurtag'), "value": t('Omurtag') },
        { "label": t('Velingrad'), "value": t('Velingrad') },
        { "label": t('Isperih'), "value": t('Isperih') },
        { "label": t('Karlovo'), "value": t('Karlovo') },
        { "label": t('Lom'), "value": t('Lom') },
        { "label": t('Panagyurishte'), "value": t('Panagyurishte') },
        { "label": t('Botevgrad'), "value": t('Botevgrad') },
        { "label": t('Peshtera'), "value": t('Peshtera') },
        { "label": t('Rakovski'), "value": t('Rakovski') },
        { "label": t('Veliki Preslav'), "value": t('Veliki Preslav') },
        { "label": t('Pomorie'), "value": t('Pomorie') },
        { "label": t('Lyaskovets'), "value": t('Lyaskovets') },
        { "label": t('Novi Pazar'), "value": t('Novi Pazar') },
        { "label": t('Provadia'), "value": t('Provadia') },
        { "label": t('Razlog'), "value": t('Razlog') },
        { "label": t('Zlatograd'), "value": t('Zlatograd') },
        { "label": t('Kozloduy'), "value": t('Kozloduy') },
        { "label": t('Kostinbrod'), "value": t('Kostinbrod') },
        { "label": t('Bankya'), "value": t('Bankya') },
        { "label": t('Stamboliyski'), "value": t('Stamboliyski') },
        { "label": t('Etropole'), "value": t('Etropole') },
        { "label": t('Devnya'), "value": t('Devnya') },
        { "label": t('Rakitovo'), "value": t('Rakitovo') },
        { "label": t('Sopot'), "value": t('Sopot') },
        { "label": t('Septemvri'), "value": t('Septemvri') },
        { "label": t('Krichim'), "value": t('Krichim') },
        { "label": t('Byala'), "value": t('Byala') },
        { "label": t('Aksakovo'), "value": t('Aksakovo') },
        { "label": t('Beloslav'), "value": t('Beloslav') },
        { "label": t('Slivnitsa'), "value": t('Slivnitsa') },
        { "label": t('Elin Pelin'), "value": t('Elin Pelin') },
        { "label": t('Madan'), "value": t('Madan') },
        { "label": t('Aydemir'), "value": t('Aydemir') },
        { "label": t('Devin'), "value": t('Devin') },
        { "label": t('Lozen'), "value": t('Lozen') },
        { "label": t('Varshets'), "value": t('Varshets') },
        { "label": t('Saedinenie'), "value": t('Saedinenie') },
        { "label": t('Bistritsa'), "value": t('Bistritsa') },
        { "label": t('Bozhurishte'), "value": t('Bozhurishte') },
        { "label": t('Suvorovo'), "value": t('Suvorovo') },
        { "label": t('Perushtitsa'), "value": t('Perushtitsa') },
        { "label": t('Dolna Banya'), "value": t('Dolna Banya') },
        { "label": t('Vetovo'), "value": t('Vetovo') },
        { "label": t('Kazichene'), "value": t('Kazichene') },
        { "label": t('Ignatievo'), "value": t('Ignatievo') },
        { "label": t('Kostandovo'), "value": t('Kostandovo') },
        { "label": t('Bukovlak'), "value": t('Bukovlak') },
        { "label": t('Koynare'), "value": t('Koynare') },
        { "label": t('Slavyanovo'), "value": t('Slavyanovo') },
        { "label": t('Kalipetrovo'), "value": t('Kalipetrovo') },
        { "label": t('Trud'), "value": t('Trud') },
        { "label": t('Sveti Vlas'), "value": t('Sveti Vlas') },
        { "label": t('Sapareva Banya'), "value": t('Sapareva Banya') },
        { "label": t('Malo Konare'), "value": t('Malo Konare') },
        { "label": t('Varbitsa'), "value": t('Varbitsa') },
        { "label": t('Marten'), "value": t('Marten') },
        { "label": t('Debelets'), "value": t('Debelets') },
        { "label": t('Vladaya'), "value": t('Vladaya') },
        { "label": t('Parvenets'), "value": t('Parvenets') },
        { "label": t('Sarnitsa'), "value": t('Sarnitsa') },
        { "label": t('Rudozem'), "value": t('Rudozem') },
        { "label": t('Topolchane'), "value": t('Topolchane') },
        { "label": t('Brestovitsa'), "value": t('Brestovitsa') },
        { "label": t('Gulyantsi'), "value": t('Gulyantsi') },
        { "label": t('Nikolaevo'), "value": t('Nikolaevo') },
        { "label": t('Rogosh'), "value": t('Rogosh') },
        { "label": t('Kran'), "value": t('Kran') },
        { "label": t('Banya'), "value": t('Banya') },
        { "label": t('Topoli'), "value": t('Topoli') },
        { "label": t('Pancharevo'), "value": t('Pancharevo') },
        { "label": t('Kamenar'), "value": t('Kamenar') },
        { "label": t('Gurkovo'), "value": t('Gurkovo') },
        { "label": t('Ivaylo'), "value": t('Ivaylo') },
        { "label": t('Sotirya'), "value": t('Sotirya') },
        { "label": t('Kableshkovo'), "value": t('Kableshkovo') },
        { "label": t('Ruen'), "value": t('Ruen') },
        { "label": t('Vetren'), "value": t('Vetren') },
        { "label": t('Dolna Oryahovitsa'), "value": t('Dolna Oryahovitsa') },
        { "label": t('Buhovo'), "value": t('Buhovo') },
        { "label": t('Kalofer'), "value": t('Kalofer') },
        { "label": t('Voluyak'), "value": t('Voluyak') },
        { "label": t('Kalekovets'), "value": t('Kalekovets') },
        { "label": t('German'), "value": t('German') },
        { "label": t('Nikolovo'), "value": t('Nikolovo') },
        { "label": t('Ravda'), "value": t('Ravda') },
        { "label": t('Glozhene'), "value": t('Glozhene') },
        { "label": t('Novo Selo'), "value": t('Novo Selo') },
        { "label": t('Kurtovo Konare'), "value": t('Kurtovo Konare') },
        { "label": t('Ablanitsa'), "value": t('Ablanitsa') },
        { "label": t('Skutare'), "value": t('Skutare') },
        { "label": t('Sadovo'), "value": t('Sadovo') },
        { "label": t('Chepintsi'), "value": t('Chepintsi') },
        { "label": t('Parvomaytsi'), "value": t('Parvomaytsi') }, { "label": t('Draganovo'), "value": t('Draganovo') },
        { "label": t('Kilifarevo'), "value": t('Kilifarevo') },
        { "label": t('Ognyanovo'), "value": t('Ognyanovo') },
        { "label": t('Valkosel'), "value": t('Valkosel') },
        { "label": t('Rakovski'), "value": t('Rakovski') },
        { "label": t('Glavinitsa'), "value": t('Glavinitsa') },
        { "label": t('Bregovo'), "value": t('Bregovo') },
        { "label": t('Svetovrachane'), "value": t('Svetovrachane') },
        { "label": t('Aheloy'), "value": t('Aheloy') },
        { "label": t('Krushare'), "value": t('Krushare') },
        { "label": t('Startsevo'), "value": t('Startsevo') },
        { "label": t('Gradina'), "value": t('Gradina') },
        { "label": t('Obzor'), "value": t('Obzor') },
        { "label": t('Batanovtsi'), "value": t('Batanovtsi') },
        { "label": t('Tsaratsovo'), "value": t('Tsaratsovo') },
        { "label": t('Borovo'), "value": t('Borovo') },
        { "label": t('Voyvodinovo'), "value": t('Voyvodinovo') },
        { "label": t('Chernogorovo'), "value": t('Chernogorovo') },
        { "label": t('Balgarovo'), "value": t('Balgarovo') },
        { "label": t('Petarch'), "value": t('Petarch') },
        { "label": t('Kokalyane'), "value": t('Kokalyane') },
        { "label": t('Dragichevo'), "value": t('Dragichevo') },
        { "label": t('Yahinovo'), "value": t('Yahinovo') },
        { "label": t('Ostrovo'), "value": t('Ostrovo') },
        { "label": t('Mokrishte'), "value": t('Mokrishte') },
        { "label": t('Kraynitsi'), "value": t('Kraynitsi') },
        { "label": t('Kostievo'), "value": t('Kostievo') },
        { "label": t('Resen'), "value": t('Resen') },
        { "label": t('Aleksandrovo'), "value": t('Aleksandrovo') },
        { "label": t('Sinitovo'), "value": t('Sinitovo') },
        { "label": t('Ezerovo'), "value": t('Ezerovo') },
        { "label": t('Graf Ignatievo'), "value": t('Graf Ignatievo') },
        { "label": t('Seliminovo'), "value": t('Seliminovo') },
        { "label": t('Uzundzhovo'), "value": t('Uzundzhovo') },
        { "label": t('Busmantsi'), "value": t('Busmantsi') },
        { "label": t('Polikrayshte'), "value": t('Polikrayshte') },
        { "label": t('Lesnovo'), "value": t('Lesnovo') },
        { "label": t('Merichleri'), "value": t('Merichleri') },
        { "label": t('Lyuben Karavelovo'), "value": t('Lyuben Karavelovo') },
        { "label": t('Divotino'), "value": t('Divotino') },
        { "label": t('Byal Izvor'), "value": t('Byal Izvor') },
        { "label": t('Kermen'), "value": t('Kermen') },
        { "label": t('Ravnets'), "value": t('Ravnets') },
        { "label": t('Kukorevo'), "value": t('Kukorevo') },
        { "label": t('Samoranovo'), "value": t('Samoranovo') },
        { "label": t('Stozher'), "value": t('Stozher') },
        { "label": t('Dzhulyunitsa'), "value": t('Dzhulyunitsa') },
        { "label": t('Zheleznitsa'), "value": t('Zheleznitsa') },
        { "label": t('Slokoshtitsa'), "value": t('Slokoshtitsa') },
        { "label": t('Orizare'), "value": t('Orizare') },
        { "label": t('Negovan'), "value": t('Negovan') },
        { "label": t('Trivoditsi'), "value": t('Trivoditsi') },
        { "label": t('Krepost'), "value": t('Krepost') },
        { "label": t('Grivitsa'), "value": t('Grivitsa') },
        { "label": t('Studena'), "value": t('Studena') },
        { "label": t('Bistritsa'), "value": t('Bistritsa') },
        { "label": t('Stratsin'), "value": t('Stratsin') },
        { "label": t('Mirovyane'), "value": t('Mirovyane') },
        { "label": t('Saraya'), "value": t('Saraya') },
        { "label": t('Planinitsa'), "value": t('Planinitsa') },
        { "label": t('Krivina'), "value": t('Krivina') },
        { "label": t('Karageorgievo'), "value": t('Karageorgievo') },
        { "label": t('Prosenik'), "value": t('Prosenik') },
        { "label": t('Vinogradets'), "value": t('Vinogradets') },
        { "label": t('Tsarev Brod'), "value": t('Tsarev Brod') },
        { "label": t('Tankovo'), "value": t('Tankovo') },
        { "label": t('Maglen'), "value": t('Maglen') },
        { "label": t('Tranak'), "value": t('Tranak') },
        { "label": t('Razhitsa'), "value": t('Razhitsa') },
        { "label": t('Dzherman'), "value": t('Dzherman') },
        { "label": t('Shipka'), "value": t('Shipka') },
        { "label": t('Basarbovo'), "value": t('Basarbovo') },
        { "label": t('Karabunar'), "value": t('Karabunar') },
        { "label": t('Benkovski'), "value": t('Benkovski') },
        { "label": t('Kosharitsa'), "value": t('Kosharitsa') },
        { "label": t('Konstantinovo'), "value": t('Konstantinovo') },
        { "label": t('Yabalchevo'), "value": t('Yabalchevo') },
        { "label": t('Galabets'), "value": t('Galabets') },
        { "label": t('Chervena Voda'), "value": t('Chervena Voda') },
        { "label": t('Veselinovo'), "value": t('Veselinovo') },
        { "label": t('Bata'), "value": t('Bata') },
        { "label": t('Rudartsi'), "value": t('Rudartsi') },
        { "label": t('Dolni Bogrov'), "value": t('Dolni Bogrov') },
        { "label": t('Aldomirovtsi'), "value": t('Aldomirovtsi') },
        { "label": t('Belogradets'), "value": t('Belogradets') },
        { "label": t('Karapelit'), "value": t('Karapelit') },
        { "label": t('Novo Selo'), "value": t('Novo Selo') },
        { "label": t('Sandrovo'), "value": t('Sandrovo') },
        { "label": t('Yabalkovo'), "value": t('Yabalkovo') },
        { "label": t('Gabrovnitsa'), "value": t('Gabrovnitsa') },
        { "label": t('Vaglen'), "value": t('Vaglen') },
        { "label": t('Vardun'), "value": t('Vardun') },
        { "label": t('Marchaevo'), "value": t('Marchaevo') },
        { "label": t('Banitsa'), "value": t('Banitsa') },
        { "label": t('Gorni Bogrov'), "value": t('Gorni Bogrov') },
        { "label": t('Semerdzhievo'), "value": t('Semerdzhievo') },
        { "label": t('Zaychar'), "value": t('Zaychar') },
        { "label": t('Voyvodovo'), "value": t('Voyvodovo') },
        { "label": t('Malevo'), "value": t('Malevo') },
        { "label": t('Opalchensko'), "value": t('Opalchensko') },
        { "label": t('Zvezditsa'), "value": t('Zvezditsa') },
        { "label": t('Marinka'), "value": t('Marinka') },
        { "label": t('Boboshevo'), "value": t('Boboshevo') },
        { "label": t('Gyulyovtsa'), "value": t('Gyulyovtsa') },
        { "label": t('Gluhar'), "value": t('Gluhar') },
        { "label": t('Hadzhievo'), "value": t('Hadzhievo') },
        { "label": t('Pisarevo'), "value": t('Pisarevo') },
        { "label": t('Vaklinovo'), "value": t('Vaklinovo') },
        { "label": t('Varbitsa'), "value": t('Varbitsa') },
        { "label": t('Kladnitsa'), "value": t('Kladnitsa') },
        { "label": t('Patalenitsa'), "value": t('Patalenitsa') },
        { "label": t('Dolen'), "value": t('Dolen') },
        { "label": t('Dobromir'), "value": t('Dobromir') },
        { "label": t('Dobri Dyal'), "value": t('Dobri Dyal') },
        { "label": t('Gorski Izvor'), "value": t('Gorski Izvor') },
        { "label": t('Stefanovo'), "value": t('Stefanovo') },
        { "label": t('Borovo'), "value": t('Borovo') },
        { "label": t('Cherven Breg'), "value": t('Cherven Breg') },
        { "label": t('Snyagovo'), "value": t('Snyagovo') },
        { "label": t('Krastava'), "value": t('Krastava') },
        { "label": t('Kadievo'), "value": t('Kadievo') },
        { "label": t('Voysil'), "value": t('Voysil') },
        { "label": t('Vresovo'), "value": t('Vresovo') },
        { "label": t('Vinitsa'), "value": t('Vinitsa') },
        { "label": t('Mortagonovo'), "value": t('Mortagonovo') },
        { "label": t('Izvorsko'), "value": t('Izvorsko') },
        { "label": t('Dobroslavtsi'), "value": t('Dobroslavtsi') },
        //new
        { "label": t('Ablanica'), "value": t('Ablanica') },
        { "label": t('Abrit'), "value": t('Abrit') },
        { "label": t('Avramovo'), "value": t('Avramovo') },
        { "label": t('Avren'), "value": t('Avren') },
        { "label": t('Agate'), "value": t('Agate') },
        { "label": t('Airovo'), "value": t('Airovo') },
        { "label": t('Akandzhievo'), "value": t('Akandzhievo') },
        { "label": t('Aksakovo'), "value": t('Aksakovo') },
        { "label": t('Alamovci'), "value": t('Alamovci') },
        { "label": t('Alvanovo'), "value": t('Alvanovo') },
        { "label": t('Aldomirovci'), "value": t('Aldomirovci') },
        { "label": t('Aleko Konstantinovo'), "value": t('Aleko Konstantinovo') },
        { "label": t('Alekovo (Veliko Tarnovo)'), "value": t('Alekovo (Veliko Tarnovo)') },
        { "label": t('Alekovo (Silistra)'), "value": t('Alekovo (Silistra)') },
        { "label": t('Alexandria'), "value": t('Alexandria') },
        { "label": t('Alexandrovo (Veliko Tarnovo)'), "value": t('Alexandrovo (Veliko Tarnovo)') },
        { "label": t('Alexandrovo (Targovishte)'), "value": t('Alexandrovo (Targovishte)') },
        { "label": t('Alexandrovo (Stara Zagora)'), "value": t('Alexandrovo (Stara Zagora)') },
        { "label": t('Alexandrovo (Shumen)'), "value": t('Alexandrovo (Shumen)') },
        { "label": t('Alexandrovo (Lovech)'), "value": t('Alexandrovo (Lovech)') },
        { "label": t('Alexandrovo (Yambol)'), "value": t('Alexandrovo (Yambol)') },
        { "label": t('Alexandrovo (Haskovo)'), "value": t('Alexandrovo (Haskovo)') },
        { "label": t('Alexandrovo (Burgas)'), "value": t('Alexandrovo (Burgas)') },
        { "label": t('Alexander Stamboliyski'), "value": t('Alexander Stamboliyski') },
        { "label": t('Alendarova'), "value": t('Alendarova') },
        { "label": t('Alino'), "value": t('Alino') },
        { "label": t('Altimir'), "value": t('Altimir') },
        { "label": t('Altsek'), "value": t('Altsek') },
        { "label": t('Angel Voivoda'), "value": t('Angel Voivoda') },
        { "label": t('Angelariy'), "value": t('Angelariy') },
        { "label": t('Angelov'), "value": t('Angelov') },
        { "label": t('Antimovo (Vidin)'), "value": t('Antimovo (Vidin)') },
        { "label": t('Antimovo (Silistra)'), "value": t('Antimovo (Silistra)') },
        { "label": t('Anton'), "value": t('Anton') },
        { "label": t('Aprilovo (Targovishte)'), "value": t('Aprilovo (Targovishte)') },
        { "label": t('Aprilovo (Stara Zagora)'), "value": t('Aprilovo (Stara Zagora)') },
        { "label": t('Aprilovo (Sofia - oblast)'), "value": t('Aprilovo (Sofia - oblast)') },
        { "label": t('Apriltsi (Pazardzhik)'), "value": t('Apriltsi (Pazardzhik)') },
        { "label": t('Arbanasi'), "value": t('Arbanasi') },
        { "label": t('Arda'), "value": t('Arda') },
        { "label": t('Arzan'), "value": t('Arzan') },
        { "label": t('Arkovna'), "value": t('Arkovna') },
        { "label": t('Armenite'), "value": t('Armenite') },
        { "label": t('Armyankovtsi'), "value": t('Armyankovtsi') },
        { "label": t('Arnautito'), "value": t('Arnautito') },
        { "label": t('Arpadzhik'), "value": t('Arpadzhik') },
        { "label": t('Archyar'), "value": t('Archyar') },
        { "label": t('Asen (Stara Zagora)'), "value": t('Asen (Stara Zagora)') },
        { "label": t('Asen (Lovech)'), "value": t('Asen (Lovech)') },
        { "label": t('Asenovets'), "value": t('Asenovets') },
        { "label": t('Asenovo (Veliko Tarnovo)'), "value": t('Asenovo (Veliko Tarnovo)') },
        { "label": t('Asenovo (Pleven)'), "value": t('Asenovo (Pleven)') },
        { "label": t('Asenovo (Yambol)'), "value": t('Asenovo (Yambol)') },
        { "label": t('Asenovtsi'), "value": t('Asenovtsi') },
        { "label": t('Asparuhovo (Varna)'), "value": t('Asparuhovo (Varna)') },
        { "label": t('Asparuhovo (Pleven)'), "value": t('Asparuhovo (Pleven)') },
        { "label": t('Asparuhovo (Montana)'), "value": t('Asparuhovo (Montana)') },
        { "label": t('Asparuhovo (Burgas)'), "value": t('Asparuhovo (Burgas)') },
        { "label": t('Atiya'), "value": t('Atiya') },
        { "label": t('Atolovo'), "value": t('Atolovo') },
        { "label": t('Austa'), "value": t('Austa') },
        { "label": t('Aheloy'), "value": t('Aheloy') },
        { "label": t('Ahmatovo'), "value": t('Ahmatovo') },
        { "label": t('Ahryansko'), "value": t('Ahryansko') },
        { "label": t('Baba Stana'), "value": t('Baba Stana') },
        { "label": t('Baba Tonka'), "value": t('Baba Tonka') },
        { "label": t('Babek'), "value": t('Babek') },
        { "label": t('Babino'), "value": t('Babino') },
        { "label": t('Babinska Reka'), "value": t('Babinska Reka') },
        { "label": t('Babinci'), "value": t('Babinci') },
        { "label": t('Babitsa'), "value": t('Babitsa') },
        { "label": t('Bablon'), "value": t('Bablon') },
        { "label": t('Babovo'), "value": t('Babovo') },
        { "label": t('Babuk'), "value": t('Babuk') },
        { "label": t('Babyak'), "value": t('Babyak') },
        { "label": t('Bagalevtsi'), "value": t('Bagalevtsi') },
        { "label": t('Bagra'), "value": t('Bagra') },
        { "label": t('Bagrentsi'), "value": t('Bagrentsi') },
        { "label": t('Bagriltsi'), "value": t('Bagriltsi') },
        { "label": t('Bagryan'), "value": t('Bagryan') },
        { "label": t('Badevtsi'), "value": t('Badevtsi') },
        { "label": t('Badino'), "value": t('Badino') },
        { "label": t('Baevtsi'), "value": t('Baevtsi') },
        { "label": t('Bazhdari'), "value": t('Bazhdari') },
        { "label": t('Baykal'), "value": t('Baykal') },
        { "label": t('Baykalsko'), "value": t('Baykalsko') },
        { "label": t('Baykovo'), "value": t('Baykovo') },
        { "label": t('Baylovo'), "value": t('Baylovo') },
        { "label": t('Bakalite'), "value": t('Bakalite') },
        { "label": t('Baykovo'), "value": t('Baykovo') },
        { "label": t('Balabanovo'), "value": t('Balabanovo') },
        { "label": t('Balabansko'), "value": t('Balabansko') },
        { "label": t('Balabanchevo'), "value": t('Balabanchevo') },
        { "label": t('Balaleya'), "value": t('Balaleya') },
        { "label": t('Balanite'), "value": t('Balanite') },
        { "label": t('Balanovo'), "value": t('Balanovo') },
        { "label": t('Balvan'), "value": t('Balvan') },
        { "label": t('Balvantsite'), "value": t('Balvantsite') },
        { "label": t('Baldevo'), "value": t('Baldevo') },
        { "label": t('Baley'), "value": t('Baley') },
        { "label": t('Balik'), "value": t('Balik') },
        { "label": t('Balkan'), "value": t('Balkan') },
        { "label": t('Balkan Mahala'), "value": t('Balkan Mahala') },
        { "label": t('Balkanets'), "value": t('Balkanets') },
        { "label": t('Balkanski'), "value": t('Balkanski') },
        { "label": t('Balkantsi (Veliko Tarnovo)'), "value": t('Balkantsi (Veliko Tarnovo)') },
        { "label": t('Balkantsi (Dobrich)'), "value": t('Balkantsi (Dobrich)') },
        { "label": t('Balutsi'), "value": t('Balutsi') },
        { "label": t('Balsha'), "value": t('Balsha') },
        { "label": t('Balovtsi'), "value": t('Balovtsi') },
        { "label": t('Balyuvitsa'), "value": t('Balyuvitsa') },
        { "label": t('Bangeytsi'), "value": t('Bangeytsi') },
        { "label": t('Banevo'), "value": t('Banevo') },
        { "label": t('Banitsa'), "value": t('Banitsa') },
        { "label": t('Banichan'), "value": t('Banichan') },
        { "label": t('Banishte'), "value": t('Banishte') },
        { "label": t('Bankovets'), "value": t('Bankovets') },
        { "label": t('Bankovtsi'), "value": t('Bankovtsi') },
        { "label": t('Bankya (Pernik)'), "value": t('Bankya (Pernik)') },
        { "label": t('Banovo'), "value": t('Banovo') },
        { "label": t('Banya (Sliven)'), "value": t('Banya (Sliven)') },
        { "label": t('Banya (Plovdiv)'), "value": t('Banya (Plovdiv)') },
        { "label": t('Banya (Pazardzhik)'), "value": t('Banya (Pazardzhik)') },
        { "label": t('Banya (Blagoevgrad)'), "value": t('Banya (Blagoevgrad)') },
        { "label": t('Banya (Burgas)'), "value": t('Banya (Burgas)') },
        { "label": t('Barakovo'), "value": t('Barakovo') },
        { "label": t('Baratsi'), "value": t('Baratsi') },
        { "label": t('Barutin'), "value": t('Barutin') },
        { "label": t('Baskaltsi'), "value": t('Baskaltsi') },
        { "label": t('Buta'), "value": t('Buta') },
        { "label": t('Batak (Veliko Tarnovo)'), "value": t('Batak (Veliko Tarnovo)') },
        { "label": t('Batin'), "value": t('Batin') },
        { "label": t('Batishnitsa'), "value": t('Batishnitsa') },
        { "label": t('Batovo'), "value": t('Batovo') },
        { "label": t('Batoshevo'), "value": t('Batoshevo') },
        { "label": t('Batuliya'), "value": t('Batuliya') },
        { "label": t('Batultsi'), "value": t('Batultsi') },
        { "label": t('Baurene'), "value": t('Baurene') },
        { "label": t('Bakhalin'), "value": t('Bakhalin') },
        { "label": t('Bakhovitsa'), "value": t('Bakhovitsa') },
        { "label": t('Bakhrezi'), "value": t('Bakhrezi') },
        { "label": t('Batsova Mahala'), "value": t('Batsova Mahala') },
        { "label": t('Bachevo'), "value": t('Bachevo') },
        { "label": t('Bachkov'), "value": t('Bachkov') },
        { "label": t('Bashevo'), "value": t('Bashevo') },
        { "label": t('Bashino (Stara Zagora)'), "value": t('Bashino (Stara Zagora)') },
        { "label": t('Bashino (Silistra)'), "value": t('Bashino (Silistra)') },
        { "label": t('Bashino (Kardzhali)'), "value": t('Bashino (Kardzhali)') },
        { "label": t('Bayachevo'), "value": t('Bayachevo') },
        { "label": t('Bdintsi'), "value": t('Bdintsi') },
        { "label": t('Bebrovo'), "value": t('Bebrovo') },
        { "label": t('Beglezh'), "value": t('Beglezh') },
        { "label": t('Begov'), "value": t('Begov') },
        { "label": t('Begunovtsi'), "value": t('Begunovtsi') },
        { "label": t('Beguntsi'), "value": t('Beguntsi') },
        { "label": t('Beden'), "value": t('Beden') },
        { "label": t('Bezhdene'), "value": t('Bezhdene') },
        { "label": t('Bezhdentsi'), "value": t('Bezhdentsi') },
        { "label": t('Bezmer (Yambol)'), "value": t('Bezmer (Yambol)') },
        { "label": t('Bezmer (Dobrich)'), "value": t('Bezmer (Dobrich)') },
        { "label": t('Bel Kamen'), "value": t('Bel Kamen') },
        { "label": t('Bela'), "value": t('Bela') },
        { "label": t('Bela Rada'), "value": t('Bela Rada') },
        { "label": t('Belanitsa'), "value": t('Belanitsa') },
        { "label": t('Belasitsa'), "value": t('Belasitsa') },
        { "label": t('Belashitsa'), "value": t('Belashitsa') },
        { "label": t('Belgun'), "value": t('Belgun') },
        { "label": t('Belev Dol'), "value": t('Belev Dol') },
        { "label": t('Belevren'), "value": t('Belevren') },
        { "label": t('Belentsi'), "value": t('Belentsi') },
        { "label": t('Beli Breg'), "value": t('Beli Breg') },
        { "label": t('Beli Brod'), "value": t('Beli Brod') },
        { "label": t('Beli Bryag'), "value": t('Beli Bryag') },
        { "label": t('Beli Vir'), "value": t('Beli Vir') },
        { "label": t('Beli Dol'), "value": t('Beli Dol') },
        { "label": t('Beli Izvor'), "value": t('Beli Izvor') },
        { "label": t('Beli Iskur'), "value": t('Beli Iskur') },
        { "label": t('Beli Lom'), "value": t('Beli Lom') },
        { "label": t('Beli Osum'), "value": t('Beli Osum') },
        { "label": t('Beli Plast'), "value": t('Beli Plast') },
        { "label": t('Belila'), "value": t('Belila') },
        { "label": t('Belimel'), "value": t('Belimel') },
        { "label": t('Belintsi'), "value": t('Belintsi') },
        { "label": t('Belitsa (Silistra)'), "value": t('Belitsa (Silistra)') },
        { "label": t('Belitsa (Sofia - oblast)'), "value": t('Belitsa (Sofia - oblast)') },
        { "label": t('Belitsa (Plovdiv)'), "value": t('Belitsa (Plovdiv)') },
        { "label": t('Belitsa (Haskovo)'), "value": t('Belitsa (Haskovo)') },
        { "label": t('Belitsa (Gabrovo)'), "value": t('Belitsa (Gabrovo)') },
        { "label": t('Belish'), "value": t('Belish') },
        { "label": t('Belo Pole (Vidin)'), "value": t('Belo Pole (Vidin)') },
        { "label": t('Belo Pole (Blagoevgrad)'), "value": t('Belo Pole (Blagoevgrad)') },
        { "label": t('Belovets'), "value": t('Belovets') },
        { "label": t('Belovitsa'), "value": t('Belovitsa') },
        { "label": t('Beronovo'), "value": t('Beronovo') },
        { "label": t('Bersin'), "value": t('Bersin') },
        { "label": t('Beslen'), "value": t('Beslen') },
        { "label": t('Bivolare'), "value": t('Bivolare') },
        { "label": t('Bivolyane'), "value": t('Bivolyane') },
        { "label": t('Bizhovtsi'), "value": t('Bizhovtsi') },
        { "label": t('Bikovo'), "value": t('Bikovo') },
        { "label": t('Bilintsi'), "value": t('Bilintsi') },
        { "label": t('Bilka'), "value": t('Bilka') },
        { "label": t('Bilkini'), "value": t('Bilkini') },
        { "label": t('Bilo'), "value": t('Bilo') },
        { "label": t('Bilyanska'), "value": t('Bilyanska') },
        { "label": t('Binkos'), "value": t('Binkos') },
        { "label": t('Birkova'), "value": t('Birkova') },
        { "label": t('Biser'), "value": t('Biser') },
        { "label": t('Biserts'), "value": t('Biserts') },
        { "label": t('Bistra (Targovishte)'), "value": t('Bistra (Targovishte)') },
        { "label": t('Bistra (Silistra)'), "value": t('Bistra (Silistra)') },
        { "label": t('Bistrentsi'), "value": t('Bistrentsi') },
        { "label": t('Bistrets (Dobrich)'), "value": t('Bistrets (Dobrich)') },
        { "label": t('Bistrets (Burgas)'), "value": t('Bistrets (Burgas)') },
        { "label": t('Bistritsa'), "value": t('Bistritsa') },
        { "label": t('Bistritsa (Sofia - grad)'), "value": t('Bistritsa (Sofia - grad)') },
        { "label": t('Bistritsa (Kyustendil)'), "value": t('Bistritsa (Kyustendil)') },
        { "label": t('Bistritsa (Blagoevgrad)'), "value": t('Bistritsa (Blagoevgrad)') },
        { "label": t('Blagovo (Shumen)'), "value": t('Blagovo (Shumen)') },
        { "label": t('Blagovo (Montana)'), "value": t('Blagovo (Montana)') },
        { "label": t('Blagoevo (Veliko Tarnovo)'), "value": t('Blagoevo (Veliko Tarnovo)') },
        { "label": t('Blagoevo (Razgrad)'), "value": t('Blagoevo (Razgrad)') },
        { "label": t('Blagun'), "value": t('Blagun') },
        { "label": t('Blazhievo'), "value": t('Blazhievo') },
        { "label": t('Blatez (Sliven)'), "value": t('Blatez (Sliven)') },
        { "label": t('Blatez (Kyustendil)'), "value": t('Blatez (Kyustendil)') },
        { "label": t('Blateshnitsa'), "value": t('Blateshnitsa') },
        { "label": t('Blatino'), "value": t('Blatino') },
        { "label": t('Blatnitsa'), "value": t('Blatnitsa') },
        { "label": t('Blato'), "value": t('Blato') },
        { "label": t('Blatska'), "value": t('Blatska') },
        { "label": t('Blenika'), "value": t('Blenika') },
        { "label": t('Bliznak'), "value": t('Bliznak') },
        { "label": t('Bliznatsi (Varna)'), "value": t('Bliznatsi (Varna)') },
        { "label": t('Bliznatsi (Shumen)'), "value": t('Bliznatsi (Shumen)') },
        { "label": t('Bliznets'), "value": t('Bliznets') },
        { "label": t('Blaskovo'), "value": t('Blaskovo') },
        { "label": t('Blaskovtsi'), "value": t('Blaskovtsi') },
        { "label": t('Boazat'), "value": t('Boazat') },
        { "label": t('Bobeshino'), "value": t('Bobeshino') },
        { "label": t('Bobovets'), "value": t('Bobovets') },
        { "label": t('Boboratsi'), "value": t('Boboratsi') },
        { "label": t('Bov (Sofia - oblast)'), "value": t('Bov (Sofia - oblast)') },
        { "label": t('Bov (Sofia - oblast)'), "value": t('Bov (Sofia - oblast)') },
        { "label": t('Bogatovo'), "value": t('Bogatovo') },
        { "label": t('Bogdan (Plovdiv)'), "value": t('Bogdan (Plovdiv)') },
        { "label": t('Bogdan (Dobrich)'), "value": t('Bogdan (Dobrich)') },
        { "label": t('Bogdanitsa'), "value": t('Bogdanitsa') },
        { "label": t('Bogdanliya'), "value": t('Bogdanliya') },
        { "label": t('Bogdanovdol'), "value": t('Bogdanovdol') },
        { "label": t('Bogdanovo (Sliven)'), "value": t('Bogdanovo (Sliven)') },
        { "label": t('Bogdanovo (Burgas)'), "value": t('Bogdanovo (Burgas)') },
        { "label": t('Bogdantsi (Silistra)'), "value": t('Bogdantsi (Silistra)') },
        { "label": t('Bogdantsi (Razgrad)'), "value": t('Bogdantsi (Razgrad)') },
        { "label": t('Bogolin'), "value": t('Bogolin') },
        { "label": t('Bogomil'), "value": t('Bogomil') },
        { "label": t('Bogomilovo'), "value": t('Bogomilovo') },
        { "label": t('Bogomoltsi'), "value": t('Bogomoltsi') },
        { "label": t('Bogoslovsko'), "value": t('Bogoslovsko') },
        { "label": t('Bogorovo (Silistra)'), "value": t('Bogorovo (Silistra)') },
        { "label": t('Bogorovo (Yambol)'), "value": t('Bogorovo (Yambol)') },
        { "label": t('Bogoslov'), "value": t('Bogoslov') },
        { "label": t('Bogutevo'), "value": t('Bogutevo') },
        { "label": t('Bogyovtsi'), "value": t('Bogyovtsi') },
        { "label": t('Bozhak'), "value": t('Bozhak') },
        { "label": t('Bozhan'), "value": t('Bozhan') },
        { "label": t('Bozhanovo'), "value": t('Bozhanovo') },
        { "label": t('Bozhdovo'), "value": t('Bozhdovo') },
        { "label": t('Bozhevtsi'), "value": t('Bozhevtsi') },
        { "label": t('Bozhenitsa'), "value": t('Bozhenitsa') },
        { "label": t('Bozhenitsite'), "value": t('Bozhenitsite') },
        { "label": t('Bozhichen'), "value": t('Bozhichen') },
        { "label": t('Bozhurets'), "value": t('Bozhurets') },
        { "label": t('Bozhuritsa'), "value": t('Bozhuritsa') },
        { "label": t('Bozhurishte'), "value": t('Bozhurishte') },
        { "label": t('Bozhurka'), "value": t('Bozhurka') },
        { "label": t('Bozhurluk'), "value": t('Bozhurluk') },
        { "label": t('Bozhurovo (Shumen)'), "value": t('Bozhurovo (Shumen)') },
        { "label": t('Bozhurovo (Razgrad)'), "value": t('Bozhurovo (Razgrad)') },
        { "label": t('Bozhurovo (Dobrich)'), "value": t('Bozhurovo (Dobrich)') },
        { "label": t('Bozhdzhii'), "value": t('Bozhdzhii') },
        { "label": t('Bozveliysko'), "value": t('Bozveliysko') },
        { "label": t('Bozduganovo'), "value": t('Bozduganovo') },
        { "label": t('Bozova'), "value": t('Bozova') },
        { "label": t('Boil'), "value": t('Boil') },
        { "label": t('Boykovets'), "value": t('Boykovets') },
        { "label": t('Boykovo'), "value": t('Boykovo') },
        { "label": t('Boykovtsi'), "value": t('Boykovtsi') },
        { "label": t('Boynik'), "value": t('Boynik') },
        { "label": t('Boynitsa'), "value": t('Boynitsa') },
        { "label": t('Boyno'), "value": t('Boyno') },
        { "label": t('Boynovtsi'), "value": t('Boynovtsi') },
        { "label": t('Boyche'), "value": t('Boyche') },
        { "label": t('Boychevtsi'), "value": t('Boychevtsi') },
        { "label": t('Bokilovtsi'), "value": t('Bokilovtsi') },
        { "label": t('Boltata'), "value": t('Boltata') },
        { "label": t('Bolyarino'), "value": t('Bolyarino') },
        { "label": t('Bolyarski izvor'), "value": t('Bolyarski izvor') },
        { "label": t('Bolyarcko'), "value": t('Bolyarcko') },
        { "label": t('Bolyaritsi (Varna)'), "value": t('Bolyaritsi (Varna)') },
        { "label": t('Bolyaritsi (Plovdiv)'), "value": t('Bolyaritsi (Plovdiv)') },
        { "label": t('Bolyaritsi (Kyustendil)'), "value": t('Bolyaritsi (Kyustendil)') },
        { "label": t('Bonevo'), "value": t('Bonevo') },
        { "label": t('Bor'), "value": t('Bor') },
        { "label": t('Borets'), "value": t('Borets') },
        { "label": t('Borie'), "value": t('Borie') },
        { "label": t('Borika (Smolyan)'), "value": t('Borika (Smolyan)') },
        { "label": t('Borika (Sofia - oblast)'), "value": t('Borika (Sofia - oblast)') },
        { "label": t('Boriki'), "value": t('Boriki') },
        { "label": t('Borikovo'), "value": t('Borikovo') },
        { "label": t('Borilovec'), "value": t('Borilovec') },
        { "label": t('Borilovo'), "value": t('Borilovo') },
        { "label": t('Borima'), "value": t('Borima') },
        { "label": t('Borimechkovo'), "value": t('Borimechkovo') },
        { "label": t('Borino'), "value": t('Borino') },
        { "label": t('Borinovo'), "value": t('Borinovo') },
        { "label": t('Borintsi'), "value": t('Borintsi') },
        { "label": t('Boriana'), "value": t('Boriana') },
        { "label": t('Bosevtsi'), "value": t('Bosevtsi') },
        { "label": t('Bosilkovo (Smolyan)'), "value": t('Bosilkovo (Smolyan)') },
        { "label": t('Bosilkovo (Burgas)'), "value": t('Bosilkovo (Burgas)') },
        { "label": t('Bosilkovtsi'), "value": t('Bosilkovtsi') },
        { "label": t('Bosna'), "value": t('Bosna') },
        { "label": t('Bosnek'), "value": t('Bosnek') },
        { "label": t('Bostan'), "value": t('Bostan') },
        { "label": t('Bostina'), "value": t('Bostina') },
        { "label": t('Botevo (Vratsa)'), "value": t('Botevo (Vratsa)') },
        { "label": t('Botevo (Varna)'), "value": t('Botevo (Varna)') },
        { "label": t('Botevo (Montana)'), "value": t('Botevo (Montana)') },
        { "label": t('Botevgrad'), "value": t('Botevgrad') },
        { "label": t('Botrov'), "value": t('Botrov') },
        { "label": t('Botunya'), "value": t('Botunya') },
        { "label": t('Boturche'), "value": t('Boturche') },
        { "label": t('Bokhova'), "value": t('Bokhova') },
        { "label": t('Bokhot'), "value": t('Bokhot') },
        { "label": t('Bochkovtsi'), "value": t('Bochkovtsi') },
        { "label": t('Boshulya'), "value": t('Boshulya') },
        { "label": t('Boyadzhik'), "value": t('Boyadzhik') },
        { "label": t('Boyan'), "value": t('Boyan') },
        { "label": t('Boyan Botevo'), "value": t('Boyan Botevo') },
        { "label": t('Boyana'), "value": t('Boyana') },
        { "label": t('Boyano'), "value": t('Boyano') },
        { "label": t('Boyanovo (Vidin)'), "value": t('Boyanovo (Vidin)') },
        { "label": t('Boyanovo (Yambol)'), "value": t('Boyanovo (Yambol)') },
        { "label": t('Boyanovtsi'), "value": t('Boyanovtsi') },
        { "label": t('Boyantsi'), "value": t('Boyantsi') },
        { "label": t('Bradvari'), "value": t('Bradvari') },
        { "label": t('Braknitsa'), "value": t('Braknitsa') },
        { "label": t('Brakyovtsi'), "value": t('Brakyovtsi') },
        { "label": t('Branipole'), "value": t('Branipole') },
        { "label": t('Branitsa'), "value": t('Branitsa') },
        { "label": t('Branichevo'), "value": t('Branichevo') },
        { "label": t('Branshte'), "value": t('Branshte') },
        { "label": t('Brankovtsi (Veliko Tarnovo)'), "value": t('Brankovtsi (Veliko Tarnovo)') },
        { "label": t('Brankovtsi (Vidin)'), "value": t('Brankovtsi (Vidin)') },
        { "label": t('Bratan'), "value": t('Bratan') },
        { "label": t('Bratanitsa'), "value": t('Bratanitsa') },
        { "label": t('Bratovo (Targovishte)'), "value": t('Bratovo (Targovishte)') },
        { "label": t('Bratovo (Burgas)'), "value": t('Bratovo (Burgas)') },
        { "label": t('Bratushovo'), "value": t('Bratushovo') },
        { "label": t('Bratya Daskalovi'), "value": t('Bratya Daskalovi') },
        { "label": t('Bratya Kunchevi'), "value": t('Bratya Kunchevi') },
        { "label": t('Bregare'), "value": t('Bregare') },
        { "label": t('Brezhani'), "value": t('Brezhani') },
        { "label": t('Brezhnitsite'), "value": t('Brezhnitsite') },
        { "label": t('Breza'), "value": t('Breza') },
        { "label": t('Breze (Smolyan)'), "value": t('Breze (Smolyan)') },
        { "label": t('Breze (Sofia - oblast)'), "value": t('Breze (Sofia - oblast)') },
        { "label": t('Brezen'), "value": t('Brezen') },
        { "label": t('Breznitsa'), "value": t('Breznitsa') },
        { "label": t('Breznishki izvor'), "value": t('Breznishki izvor') },
        { "label": t('Brezovdol'), "value": t('Brezovdol') },
        { "label": t('Brezovo (Veliko Tarnovo)'), "value": t('Brezovo (Veliko Tarnovo)') },
        { "label": t('Brezovo (Lovech)'), "value": t('Brezovo (Lovech)') },
        { "label": t('Brenitsa (Pleven)'), "value": t('Brenitsa (Pleven)') },
        { "label": t('Brenitsa (Silistra)'), "value": t('Brenitsa (Silistra)') },
        { "label": t('Brest (Pleven)'), "value": t('Brest (Pleven)') },
        { "label": t('Brest (Kyustendil)'), "value": t('Brest (Kyustendil)') },
        { "label": t('Brestak'), "value": t('Brestak') },
        { "label": t('Breste'), "value": t('Breste') },
        { "label": t('Brestnik'), "value": t('Brestnik') },
        { "label": t('Brestnitsa (Lovech)'), "value": t('Brestnitsa (Lovech)') },
        { "label": t('Brestnitsa (Dobrich)'), "value": t('Brestnitsa (Dobrich)') },
        { "label": t('Brestovene'), "value": t('Brestovene') },
        { "label": t('Brestovets'), "value": t('Brestovets') },
        { "label": t('Brestovitsa (Ruse)'), "value": t('Brestovitsa (Ruse)') },
        { "label": t('Brestovitsa (Plovdiv)'), "value": t('Brestovitsa (Plovdiv)') },
        { "label": t('Brestovo (Lovech)'), "value": t('Brestovo (Lovech)') },
        { "label": t('Brestovo (Blagoevgrad)'), "value": t('Brestovo (Blagoevgrad)') },
        { "label": t('Brod'), "value": t('Brod') },
        { "label": t('Brodilovo'), "value": t('Brodivolo') },
        { "label": t('Brusevtsi'), "value": t('Brusevtsi') },
        { "label": t('Brusen (Vratsa)'), "value": t('Brusen (Vratsa)') },
        { "label": t('Brusen (Sofia - oblast)'), "value": t('Brusen (Sofia - oblast)') },
        { "label": t('Brusino'), "value": t('Brusino') },
        { "label": t('Brusnik'), "value": t('Brusnik') },
        { "label": t('Brachkovtsi (Veliko Tarnovo)'), "value": t('Brachkovtsi (Veliko Tarnovo)') },
        { "label": t('Brashlen'), "value": t('Brashlen') },
        { "label": t('Brashlyan'), "value": t('Brashlyan') },
        { "label": t('Brashlyanitsa'), "value": t('Brashlyanitsa') },
        { "label": t('Brashten'), "value": t('Brashten') },
        { "label": t('Bryagovets'), "value": t('Bryagovets') },
        { "label": t('Bryagovitsa'), "value": t('Bryagovitsa') },
        { "label": t('Bryagovo (Plovdiv)'), "value": t('Bryagovo (Plovdiv)') },
        { "label": t('Bryagovo (Haskovo)'), "value": t('Bryagovo (Haskovo)') },
        { "label": t('Bryast'), "value": t('Bryast') },
        { "label": t('Bryastovets'), "value": t('Bryastovets') },
        { "label": t('Bryastovo (Sliven)'), "value": t('Bryastovo (Sliven)') },
        { "label": t('Bryastovo (Haskovo)'), "value": t('Bryastovo (Haskovo)') },
        { "label": t('Bryastovo (Dobrich)'), "value": t('Bryastovo (Dobrich)') },
        { "label": t('Bubino'), "value": t('Bubino') },
        { "label": t('Budiltsi'), "value": t('Budiltsi') },
        { "label": t('Buzovgrad'), "value": t('Buzovgrad') },
        { "label": t('Buziakotsi'), "value": t('Buziakotsi') },
        { "label": t('Buynovitsa'), "value": t('Buynovitsa') },
        { "label": t('Buynovo (Smolyan)'), "value": t('Buynovo (Smolyan)') },
        { "label": t('Buynovo (Targovishte)'), "value": t('Buynovo (Targovishte)') },
        { "label": t('Buynovtsi'), "value": t('Buynovtsi') },
        { "label": t('Buk'), "value": t('Buk') },
        { "label": t('Bukak'), "value": t('Bukak') },
        { "label": t('Bukata'), "value": t('Bukata') },
        { "label": t('Bukatsite'), "value": t('Bukatsite') },
        { "label": t('Bukova Polyana'), "value": t('Bukova Polyana') },
        { "label": t('Bukovets (Veliko Tarnovo)'), "value": t('Bukovets (Veliko Tarnovo)') },
        { "label": t('Bukovets (Vratsa)'), "value": t('Bukovets (Vratsa)') },
        { "label": t('Bukovets (Vidin)'), "value": t('Bukovets (Vidin)') },
        { "label": t('Bukovets (Sofia - oblast)'), "value": t('Bukovets (Sofia - oblast)') },
        { "label": t('Bukovets (Montana)'), "value": t('Bukovets (Montana)') },
        { "label": t('Bukovlak'), "value": t('Bukovlak') },
        { "label": t('Bukovo (Smolyan)'), "value": t('Bukovo (Smolyan)') },
        { "label": t('Bukovo (Plovdiv)'), "value": t('Bukovo (Plovdiv)') },
        { "label": t('Bukovo (Blagoevgrad)'), "value": t('Bukovo (Blagoevgrad)') },
        { "label": t('Bukorovtsi'), "value": t('Bukorovtsi') },
        { "label": t('Bulair'), "value": t('Bulair') },
        { "label": t('Bunovo (Sofia - oblast)'), "value": t('Bunovo (Sofia - oblast)') },
        { "label": t('Bunovo (Kyustendil)'), "value": t('Bunovo (Kyustendil)') },
        { "label": t('Buntsevo'), "value": t('Buntsevo') },
        { "label": t('Buranovo'), "value": t('Buranovo') },
        { "label": t('Burevo'), "value": t('Burevo') },
        { "label": t('Burya'), "value": t('Burya') },
        { "label": t('Busintsi'), "value": t('Busintsi') },
        { "label": t('Busmantsi'), "value": t('Busmantsi') },
        { "label": t('Butan'), "value": t('Butan') },
        { "label": t('Butovo'), "value": t('Butovo') },
        { "label": t('Butreva'), "value": t('Butreva') },
        { "label": t('Butrointsi'), "value": t('Butrointsi') },
        { "label": t('Bukhovtsi'), "value": t('Bukhovtsi') },
        { "label": t('Buchin Prokhod'), "value": t('Buchin Prokhod') },
        { "label": t('Buchino'), "value": t('Buchino') },
        { "label": t('Buchukovtsi'), "value": t('Buchukovtsi') },
        { "label": t('Budche'), "value": t('Budche') },
        { "label": t('Buzhanka'), "value": t('Buzhanka') },
        { "label": t('Buzhentsi'), "value": t('Buzhentsi') },
        { "label": t('Buzhkovtsi'), "value": t('Buzhkovtsi') },
        { "label": t('Byaga'), "value": t('Byaga') },
        { "label": t('Byal Bryag'), "value": t('Byal Bryag') },
        { "label": t('Byal Izvor (Stara Zagora)'), "value": t('Byal Izvor (Stara Zagora)') },
        { "label": t('Byal Izvor (Kardzhali)'), "value": t('Byal Izvor (Kardzhali)') },
        { "label": t('Byal Kladenets (Sliven)'), "value": t('Byal Kladenets (Sliven)') },
        { "label": t('Byal Kladenets (Haskovo)'), "value": t('Byal Kladenets (Haskovo)') },
        { "label": t('Byala (Sliven)'), "value": t('Byala (Sliven)') },
        { "label": t('Byala Voda (Pleven)'), "value": t('Byala Voda (Pleven)') },
        { "label": t('Byala Voda (Burgas)'), "value": t('Byala Voda (Burgas)') },
        { "label": t('Byala Palanka'), "value": t('Byala Palanka') },
        { "label": t('Byala Polyana'), "value": t('Byala Polyana') },
        { "label": t('Byala Reka (Veliko Tarnovo)'), "value": t('Byala Reka (Veliko Tarnovo)') },
        { "label": t('Byala Reka (Smolyan)'), "value": t('Byala Reka (Smolyan)') },
        { "label": t('Byala Reka (Shumen)'), "value": t('Byala Reka (Shumen)') },
        { "label": t('Byala Reka (Plovdiv)'), "value": t('Byala Reka (Plovdiv)') },
        { "label": t('Byalgradets'), "value": t('Byalgradets') },
        { "label": t('Byalka'), "value": t('Byalka') },
        { "label": t('Byalkovtsi'), "value": t('Byalkovtsi') },
        { "label": t('Byalo Pole'), "value": t('Byalo Pole') },
        { "label": t('Vazovo'), "value": t('Vazovo') },
        { "label": t('Vakarel'), "value": t('Vakarel') },
        { "label": t('Vaklino'), "value": t('Vaklino') },
        { "label": t('Vaklinovo'), "value": t('Vaklinovo') },
        { "label": t('Vaksevo'), "value": t('Vaksevo') },
        { "label": t('Valevtsi'), "value": t('Valevtsi') },
        { "label": t('Varana'), "value": t('Varana') },
        { "label": t('Varvara (Pazardzhik)'), "value": t('Varvara (Pazardzhik)') },
        { "label": t('Varvara (Burgas)'), "value": t('Varvara (Burgas)') },
        { "label": t('Vardim'), "value": t('Vardim') },
        { "label": t('Vardun'), "value": t('Vardun') },
        { "label": t('Varnentsi'), "value": t('Varnentsi') },
        { "label": t('Varnik'), "value": t('Varnik') },
        { "label": t('Varovnik'), "value": t('Varovnik') },
        { "label": t('Vasil Drumev'), "value": t('Vasil Drumev') },
        { "label": t('Vasil Levski (Targovishte)'), "value": t('Vasil Levski (Targovishte)') },
        { "label": t('Vasil Levski (Stara Zagora)'), "value": t('Vasil Levski (Stara Zagora)') },
        { "label": t('Vasil Levski (Silistra)'), "value": t('Vasil Levski (Silistra)') },
        { "label": t('Vasil Levski (Plovdiv)'), "value": t('Vasil Levski (Plovdiv)') },
        { "label": t('Vasilevo'), "value": t('Vasilevo') },
        { "label": t('Vasilovtsi (Sofia - oblast)'), "value": t('Vasilovtsi (Sofia - oblast)') },
        { "label": t('Vasilovtsi (Montana)'), "value": t('Vasilovtsi (Montana)') },
        { "label": t('Vasilyovo'), "value": t('Vasilyovo') },
        { "label": t('Vaskovo'), "value": t('Vaskovo') },
        { "label": t('Vedrare'), "value": t('Vedrare') },
        { "label": t('Vedrina'), "value": t('Vedrina') },
        { "label": t('Vedrovo'), "value": t('Vedrovo') },
        { "label": t('Vezhenkovo'), "value": t('Vezhenkovo') },
        { "label": t('Veleshtani'), "value": t('Veleshtani') },
        { "label": t('Velika'), "value": t('Velika') },
        { "label": t('Velikan'), "value": t('Velikan') },
        { "label": t('Velikdenche (Targovishte)'), "value": t('Velikdenche (Targovishte)') },
        { "label": t('Velikdenche (Kardzhali)'), "value": t('Velikdenche (Kardzhali)') },
        { "label": t('Velikovo (Stara Zagora)'), "value": t('Velikovo (Stara Zagora)') },
        { "label": t('Velikovo (Dobrich)'), "value": t('Velikovo (Dobrich)') },
        { "label": t('Velikovtsi'), "value": t('Velikovtsi') },
        { "label": t('Velino'), "value": t('Velino') },
        { "label": t('Velinovo'), "value": t('Velinovo') },
        { "label": t('Velislav'), "value": t('Velislav') },
        { "label": t('Velichka'), "value": t('Velichka') },
        { "label": t('Velichkovo (Varna)'), "value": t('Velichkovo (Varna)') },
        { "label": t('Velichkovo (Pazardzhik)'), "value": t('Velichkovo (Pazardzhik)') },
        { "label": t('Velkovtsi (Veliko Tarnovo)'), "value": t('Velkovtsi (Veliko Tarnovo)') },
        { "label": t('Velkovtsi (Pernik)'), "value": t('Velkovtsi (Pernik)') },
        { "label": t('Velkovtsi (Gabrovo)'), "value": t('Velkovtsi (Gabrovo)') },
        { "label": t('Velchevo (Veliko Tarnovo)'), "value": t('Velchevo (Veliko Tarnovo)') },
        { "label": t('Velchevo (Lovech)'), "value": t('Velchevo (Lovech)') },
        { "label": t('Velchovtsi'), "value": t('Velchovtsi') },
        { "label": t('Velovo'), "value": t('Velovo') },
        { "label": t('Velyuvtsi'), "value": t('Velyuvtsi') },
        { "label": t('Velyutse'), "value": t('Velyutse') },
        { "label": t('Venelin'), "value": t('Venelin') },
        { "label": t('Venets (Stara Zagora)'), "value": t('Venets (Stara Zagora)') },
        { "label": t('Venets (Burgas)'), "value": t('Venets (Burgas)') },
        { "label": t('Venets (Shumen)'), "value": t('Venets (Shumen)') },
        { "label": t('Venkovets'), "value": t('Venkovets') },
        { "label": t('Venchansko'), "value": t('Venchansko') },
        { "label": t('Veren'), "value": t('Veren') },
        { "label": t('Verentsi'), "value": t('Verentsi') },
        { "label": t('Verinsko'), "value": t('Verinsko') },
        { "label": t('Versko'), "value": t('Versko') },
        { "label": t('Veselets (Targovishte)'), "value": t('Veselets (Targovishte)') },
        { "label": t('Veselets (Razgrad)'), "value": t('Veselets (Razgrad)') },
        { "label": t('Veselie'), "value": t('Veselie') },
        { "label": t('Veselina (Veliko Tarnovo)'), "value": t('Veselina (Veliko Tarnovo)') },
        { "label": t('Veselina (Razgrad)'), "value": t('Veselina (Razgrad)') },
        { "label": t('Veselinovo (Shumen)'), "value": t('Veselinovo (Shumen)') },
        { "label": t('Veselinovo (Yambol)'), "value": t('Veselinovo (Yambol)') },
        { "label": t('Veslets'), "value": t('Veslets') },
        { "label": t('Vetren (Stara Zagora)'), "value": t('Vetren (Stara Zagora)') },
        { "label": t('Vetren (Silistra)'), "value": t('Vetren (Silistra)') },
        { "label": t('Vetren (Pazardzhik)'), "value": t('Vetren (Pazardzhik)') },
        { "label": t('Vetren (Kyustendil)'), "value": t('Vetren (Kyustendil)') },
        { "label": t('Vetren (Burgas)'), "value": t('Vetren (Burgas)') },
        { "label": t('Vetren Dol'), "value": t('Vetren Dol') },
        { "label": t('Vetrino'), "value": t('Vetrino') },
        { "label": t('Vetrinzi'), "value": t('Vetrinzi') },
        { "label": t('Vetrushka'), "value": t('Vetrushka') },
        { "label": t('Vehtino'), "value": t('Vehtino') },
        { "label": t('Vehtovo'), "value": t('Vehtovo') },
        { "label": t('Veshtitsa'), "value": t('Veshtitsa') },
        { "label": t('Viden'), "value": t('Viden') },
        { "label": t('Vidintsi'), "value": t('Vidintsi') },
        { "label": t('Vidlitza'), "value": t('Vidlitza') },
        { "label": t('Vidno'), "value": t('Vidno') },
        { "label": t('Vidrar'), "value": t('Vidrar') },
        { "label": t('Vidrare'), "value": t('Vidrare') },
        { "label": t('Vidritsa'), "value": t('Vidritsa') },
        { "label": t('Vievo'), "value": t('Vievo') },
        { "label": t('Vizitsa'), "value": t('Vizitsa') },
        { "label": t('Vinarovo_Vidin'), "value": t('Vinarovo_Vidin') },
        { "label": t('Vinarovo_Stara_Zagora'), "value": t('Vinarovo_Stara_Zagora') },
        { "label": t('Vinarsko'), "value": t('Vinarsko') },
        { "label": t('Vinevo'), "value": t('Vinevo') },
        { "label": t('Vinitza'), "value": t('Vinitza') },
        { "label": t('Vinishte'), "value": t('Vinishte') },
        { "label": t('Vinograd'), "value": t('Vinograd') },
        { "label": t('Vinogradets'), "value": t('Vinogradets') },
        { "label": t('Vinogradi'), "value": t('Vinogradi') },
        { "label": t('Virove'), "value": t('Virove') },
        { "label": t('Virovsko'), "value": t('Virovsko') },
        { "label": t('Vis'), "value": t('Vis') },
        { "label": t('Viskyar'), "value": t('Viskyar') },
        { "label": t('Visok'), "value": t('Visok') },
        { "label": t('Visoka_Mogila'), "value": t('Visoka_Mogila') },
        { "label": t('Visoka_Polyana_Shumen'), "value": t('Visoka_Polyana_Shumen') },
        { "label": t('Visoka_Polyana_Kurdzhali'), "value": t('Visoka_Polyana_Kurdzhali') },
        { "label": t('Vitanovtsi'), "value": t('Vitanovtsi') },
        { "label": t('Vitina'), "value": t('Vitina') },
        { "label": t('Vihren'), "value": t('Vihren') },
        { "label": t('Vichovo'), "value": t('Vichovo') },
        { "label": t('Vishan'), "value": t('Vishan') },
        { "label": t('Vislene'), "value": t('Vislene') },
        { "label": t('Visna'), "value": t('Visna') },
        { "label": t('Vishnevo'), "value": t('Vishnevo') },
        { "label": t('Vishovgrad'), "value": t('Vishovgrad') },
        { "label": t('Vladaya'), "value": t('Vladaya') },
        { "label": t('Vladimir'), "value": t('Vladimir') },
        { "label": t('Vladimirovo_Montana'), "value": t('Vladimirovo_Montana') },
        { "label": t('Vladimirovo_Haskovo'), "value": t('Vladimirovo_Haskovo') },
        { "label": t('Vladimirovo_Dobrich'), "value": t('Vladimirovo_Dobrich') },
        { "label": t('Vladimirovtsi'), "value": t('Vladimirovtsi') },
        { "label": t('Vladinya'), "value": t('Vladinya') },
        { "label": t('Vladislav'), "value": t('Vladislav') },
        { "label": t('Vladislavtsi'), "value": t('Vladislavtsi') },
        { "label": t('Vladichenitsi'), "value": t('Vladichenitsi') },
        { "label": t('Vlado_Trichkov'), "value": t('Vlado_Trichkov') },
        { "label": t('Vlaychovtsi'), "value": t('Vlaychovtsi') },
        { "label": t('Vlasatili'), "value": t('Vlasatili') },
        { "label": t('Vlasatitsa'), "value": t('Vlasatitsa') },
        { "label": t('Vlakhi'), "value": t('Vlakhi') },
        { "label": t('Vlakhovo'), "value": t('Vlakhovo') },
        { "label": t('Voden_Plovdiv'), "value": t('Voden_Plovdiv') },
        { "label": t('Voden_Yambol'), "value": t('Voden_Yambol') },
        { "label": t('Voden_Haskovo'), "value": t('Voden_Haskovo') },
        { "label": t('Vodenichane'), "value": t('Vodenichane') },
        { "label": t('Vodenicharovо'), "value": t('Vodenicharovо') },
        { "label": t('Vodenitsa_Varna'), "value": t('Vodenitsa_Varna') },
        { "label": t('Vodenitsa_Targovishte'), "value": t('Vodenitsa_Targovishte') },
        { "label": t('Vodna'), "value": t('Vodna') },
        { "label": t('Vodni_Pad'), "value": t('Vodni_Pad') },
        { "label": t('Vodno_Veliko_Tarnovo'), "value": t('Vodno_Veliko_Tarnovo') },
        { "label": t('Vodno_Silistra'), "value": t('Vodno_Silistra') },
        { "label": t('Vodnyantsi_Vidin'), "value": t('Vodnyantsi_Vidin') },
        { "label": t('Vodnyantsi_Dobrich'), "value": t('Vodnyantsi_Dobrich') },
        { "label": t('Vodozabor'), "value": t('Vodozabor') },
        { "label": t('Voinikha'), "value": t('Voinikha') },
        { "label": t('Voivoda'), "value": t('Voivoda') },
        { "label": t('Voivodentsi'), "value": t('Voivodentsi') },
        { "label": t('Voivodino'), "value": t('Voivodino') },
        { "label": t('Voivodinovo'), "value": t('Voivodinovo') },
        { "label": t('Voivodovo_Vratsa'), "value": t('Voivodovo_Vratsa') },
        { "label": t('Voivodovo_Haskovo'), "value": t('Voivodovo_Haskovo') },
        { "label": t('Voikova_Laka'), "value": t('Voikova_Laka') },
        { "label": t('Voinegovtsi'), "value": t('Voinegovtsi') },
        { "label": t('Voinegovtsi'), "value": t('Voinegovtsi') },
        { "label": t('Voinezha'), "value": t('Voinezha') },
        { "label": t('Voynika'), "value": t('Voynika') },
        { "label": t('Voynikovo'), "value": t('Voynikovo') },
        { "label": t('Voynitsa'), "value": t('Voynitsa') },
        { "label": t('Voynitsi'), "value": t('Voynitsi') },
        { "label": t('Voynishka'), "value": t('Voynishka') },
        { "label": t('Voynovo'), "value": t('Voynovo') },
        { "label": t('Voynyagovo'), "value": t('Voynyagovo') },
        { "label": t('Voysil'), "value": t('Voysil') },
        { "label": t('Vokil'), "value": t('Vokil') },
        { "label": t('Volno'), "value": t('Volno') },
        { "label": t('Volovarovo'), "value": t('Volovarovo') },
        { "label": t('Volovartsi'), "value": t('Volovartsi') },
        { "label": t('Volovo'), "value": t('Volovo') },
        { "label": t('Voluyak'), "value": t('Voluyak') },
        { "label": t('Voneshta Voda'), "value": t('Voneshta Voda') },
        { "label": t('Vrabeevo'), "value": t('Vrabeevo') },
        { "label": t('Vrabtsite'), "value": t('Vrabtsite') },
        { "label": t('Vrabcha'), "value": t('Vrabcha') },
        { "label": t('Vrakupovitsa'), "value": t('Vrakupovitsa') },
        { "label": t('Vranentsi'), "value": t('Vranentsi') },
        { "label": t('Vrani Kon'), "value": t('Vrani Kon') },
        { "label": t('Vranilovtsi'), "value": t('Vranilovtsi') },
        { "label": t('Vranino'), "value": t('Vranino') },
        { "label": t('Vranintsy'), "value": t('Vranintsy') },
        { "label": t('Vransko'), "value": t('Vransko') },
        { "label": t('Vranya'), "value": t('Vranya') },
        { "label": t('Vranya Stena'), "value": t('Vranya Stena') },
        { "label": t('Vranyak'), "value": t('Vranyak') },
        { "label": t('Vrata'), "value": t('Vrata') },
        { "label": t('Vratatite'), "value": t('Vratatite') },
        { "label": t('Vratitsa'), "value": t('Vratitsa') },
        { "label": t('Vratsa'), "value": t('Vratsa') },
        { "label": t('Vrachantsi'), "value": t('Vrachantsi') },
        { "label": t('Vrachesht'), "value": t('Vrachesht') },
        { "label": t('Vrelo'), "value": t('Vrelo') },
        { "label": t('Vresovo'), "value": t('Vresovo') }, { "label": t('Vrav'), "value": t('Vrav') },
        { "label": t('Vradlovtsi'), "value": t('Vradlovtsi') },
        { "label": t('Vsemirtsi'), "value": t('Vsemirtsi') },
        { "label": t('Vukan'), "value": t('Vukan') },
        { "label": t('Vukovo'), "value": t('Vukovo') },
        { "label": t('Vabel'), "value": t('Vabel') },
        { "label": t('Vglarovo'), "value": t('Vglarovo') },
        { "label": t('Vglevtsi'), "value": t('Vglevtsi') },
        { "label": t('Vglen (Varna Province)'), "value": t('Vglen (Varna Province)') },
        { "label": t('Vglen (Sliven Province)'), "value": t('Vglen (Sliven Province)') },
        { "label": t('Vulkan'), "value": t('Vulkan') },
        { "label": t('Vulkovich'), "value": t('Vulkovich') },
        { "label": t('Vulkovo'), "value": t('Vulkovo') },
        { "label": t('Vulkosel'), "value": t('Vulkosel') },
        { "label": t('Valnari'), "value": t('Valnari') },
        { "label": t('Valcha Polyana'), "value": t('Valcha Polyana') },
        { "label": t('Valchan'), "value": t('Valchan') },
        { "label": t('Valchan Dol'), "value": t('Valchan Dol') },
        { "label": t('Valchanka'), "value": t('Valchanka') },
        { "label": t('Valchanovo'), "value": t('Valchanovo') },
        { "label": t('Valche Pole'), "value": t('Valche Pole') },
        { "label": t('Valchek'), "value": t('Valchek') },
        { "label": t('Valchi Izvor'), "value": t('Valchi Izvor') },
        { "label": t('Valchin'), "value": t('Valchin') },
        { "label": t('Valchitran'), "value": t('Valchitran') },
        { "label": t('Valchovtsi (Veliko Tarnovo Province)'), "value": t('Valchovtsi (Veliko Tarnovo Province)') },
        { "label": t('Valchovtsi (Veliko Tarnovo Province)'), "value": t('Valchovtsi (Veliko Tarnovo Province)') },
        { "label": t('Varba (Vidin Province)'), "value": t('Varba (Vidin Province)') },
        { "label": t('Varba (Smolyan Province)'), "value": t('Varba (Smolyan Province)') },
        { "label": t('Varbak'), "value": t('Varbak') },
        { "label": t('Varben (Plovdiv Province)'), "value": t('Varben (Plovdiv Province)') },
        { "label": t('Varben (Kardzhali Province)'), "value": t('Varben (Kardzhali Province)') },
        { "label": t('Varbeshnitsa'), "value": t('Varbeshnitsa') },
        { "label": t('Varbina'), "value": t('Varbina') },
        { "label": t('Varbino'), "value": t('Varbino') },
        { "label": t('Varbitsa (Veliko Tarnovo Province)'), "value": t('Varbitsa (Veliko Tarnovo Province)') },
        { "label": t('Varbitsa (Vratsa Province)'), "value": t('Varbitsa (Vratsa Province)') },
        { "label": t('Varbitsa (Pleven Province)'), "value": t('Varbitsa (Pleven Province)') },
        { "label": t('Varbitsa (Haskovo Province)'), "value": t('Varbitsa (Haskovo Province)') },
        { "label": t('Varbnitsa'), "value": t('Varbnitsa') },
        { "label": t('Varbovka'), "value": t('Varbovka') },
        { "label": t('Varbovo (Vidin Province)'), "value": t('Varbovo (Vidin Province)') },
        { "label": t('Varbovo (Smolyan Province)'), "value": t('Varbovo (Smolyan Province)') },
        { "label": t('Varbovo (Haskovo Province)'), "value": t('Varbovo (Haskovo Province)') },
        { "label": t('Varbovchets'), "value": t('Varbovchets') },
        { "label": t('Varbyane'), "value": t('Varbyane') },
        { "label": t('Varzulitsa'), "value": t('Varzulitsa') },
        { "label": t('Varli Dol (Smolyan Province)'), "value": t('Varli Dol (Smolyan Province)') },
        { "label": t('Varli Dol (Kardzhali Province)'), "value": t('Varli Dol (Kardzhali Province)') },
        { "label": t('Varlino'), "value": t('Varlino') },
        { "label": t('Varlishte'), "value": t('Varlishte') },
        { "label": t('Vartop'), "value": t('Vartop') },
        { "label": t('Varhari (Kardzhali Province)'), "value": t('Varhari (Kardzhali Province)') },
        { "label": t('Varhari (Blagoevgrad Province)'), "value": t('Varhari (Blagoevgrad Province)') },
        { "label": t('Varshilo'), "value": t('Varshilo') },
    ];

    return cities;
};

export default CitySelector;
